<?php

/**
 * PluginPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPage');
    }

    public function retrieveOneByMenuIdAndCulture($menu_id, $culture = 'fr'){
        $q = $this->createQuery('a')
	    ->leftJoin('a.Translation t')
        ->where('a.menu_id = ?', $menu_id)
	    ->andWhere('t.lang = ?', $culture);

        return $q->fetchOne();
    }
}