<?php

/**
 * PluginMenuTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMenu');
    }

    public function retrieveMenuRootForCulture($root_slug, $culture = 'fr')
    {
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);
        $this->addActiveQuery($q);

        $q->andwhere('t.slug = ?', $root_slug)
          ->andWhere('a.level = ?', 0);

        return $q->fetchOne();
    }

    public function retrieveMenuForCulture($slug, $culture = 'fr')
    {
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);
        $this->addActiveQuery($q);

        $q->andwhere('t.slug = ?', $slug);

        return $q->fetchOne();
    }

    public function retrieveLevel1ForRootIdAndCulture($root_id, $culture = 'fr')
    {
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);
        $this->addActiveQuery($q);
        $this->addSortQuery($q);

        $q->andWhere('a.root_id = ?', $root_id)
            ->andWhere('a.level = ?', 1);

        return $q->execute();
    }

    public function retrieveBySlug($slug, $culture = 'fr')
    {
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);

        $q->andWhere('t.slug = ?', $slug);

        return $q->fetchOne();
    }

    public function retrieveOneByIdAndCulture($id, $culture = 'fr')
    {
        $q = $this->createQuery('a');

        $this->addCultureQuery($q, $culture);

        $q->andWhere('a.id = ?', $id);


        return $q->fetchOne();
    }

    protected function addSortQuery(Doctrine_Query $q = null)
    {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('Menu m');
        }

        $q->addOrderBy('root_id, lft', 'asc');

        return $q;
    }

    protected function addCultureQuery(Doctrine_Query $q = null, $culture)
    {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('Menu m');
        }

        $alias = $q->getRootAlias();

        $q->leftJoin($alias . '.Translation t')
            ->andWhere('t.lang = ?', $culture);

        return $q;
    }

    protected function addActiveQuery(Doctrine_Query $q = null)
    {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('Menu m');
        }

        $q->andWhere('a.enabled = ?', Menu::ENABLED);

        return $q;
    }
}